from PyQt5 import QtCore, QtGui, QtWidgets


class Control(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 654)
        #TODO: Eliminar bordes y botones del sistema
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        
        MainWindow.setMinimumSize(QtCore.QSize(1024, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        MainWindow.setStyleSheet(self.stylos()) #* Inyect los Estylos
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_cabecera = QtWidgets.QFrame(self.centralwidget)
        self.frame_cabecera.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_cabecera.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cabecera.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cabecera.setObjectName("frame_cabecera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_cabecera)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.frame_cabecera)
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PB_menu = QtWidgets.QPushButton(self.frame)
        self.PB_menu.setMinimumSize(QtCore.QSize(60, 0))
        self.PB_menu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.PB_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iconos/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_menu.setIcon(icon)
        self.PB_menu.setIconSize(QtCore.QSize(20, 20))
        self.PB_menu.setObjectName("PB_menu")
        self.horizontalLayout_2.addWidget(self.PB_menu)
        self.horizontalLayout.addWidget(self.frame)
        spacerItem = QtWidgets.QSpacerItem(475, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_2 = QtWidgets.QFrame(self.frame_cabecera)
        self.frame_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PB_minim = QtWidgets.QPushButton(self.frame_2)
        self.PB_minim.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PB_minim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_minim.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Iconos/Minimizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_minim.setIcon(icon1)
        self.PB_minim.setObjectName("PB_minim")
        self.horizontalLayout_3.addWidget(self.PB_minim)
        self.PB_maxim = QtWidgets.QPushButton(self.frame_2)
        self.PB_maxim.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PB_maxim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_maxim.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Iconos/Maximizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_maxim.setIcon(icon2)
        self.PB_maxim.setObjectName("PB_maxim")
        self.horizontalLayout_3.addWidget(self.PB_maxim)
        self.PB_cerrar = QtWidgets.QPushButton(self.frame_2)
        self.PB_cerrar.setMaximumSize(QtCore.QSize(50, 16777215))
        self.PB_cerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Iconos/Cerrar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_cerrar.setIcon(icon3)
        self.PB_cerrar.setObjectName("PB_cerrar")
        self.horizontalLayout_3.addWidget(self.PB_cerrar)
        self.horizontalLayout.addWidget(self.frame_2)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 8)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addWidget(self.frame_cabecera)
        self.frame_cuerpo = QtWidgets.QFrame(self.centralwidget)
        self.frame_cuerpo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cuerpo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cuerpo.setObjectName("frame_cuerpo")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_cuerpo)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_menucontroles = QtWidgets.QFrame(self.frame_cuerpo)
        self.frame_menucontroles.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_menucontroles.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_menucontroles.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menucontroles.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menucontroles.setObjectName("frame_menucontroles")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_menucontroles)
        self.verticalLayout_7.setContentsMargins(2, 0, 3, 0)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.PB_logo2 = QtWidgets.QPushButton(self.frame_menucontroles)
        self.PB_logo2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.PB_logo2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Iconos/LoogoBlanco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_logo2.setIcon(icon4)
        self.PB_logo2.setIconSize(QtCore.QSize(180, 180))
        self.PB_logo2.setObjectName("PB_logo2")
        self.verticalLayout_7.addWidget(self.PB_logo2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 79, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.PB_produc = QtWidgets.QPushButton(self.frame_menucontroles)
        self.PB_produc.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_produc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Iconos/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_produc.setIcon(icon5)
        self.PB_produc.setObjectName("PB_produc")
        self.verticalLayout_7.addWidget(self.PB_produc)
        self.PB_test = QtWidgets.QPushButton(self.frame_menucontroles)
        self.PB_test.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_test.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Iconos/Test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_test.setIcon(icon6)
        self.PB_test.setObjectName("PB_test")
        self.verticalLayout_7.addWidget(self.PB_test)
        self.PB_config = QtWidgets.QPushButton(self.frame_menucontroles)
        self.PB_config.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_config.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Iconos/Config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_config.setIcon(icon7)
        self.PB_config.setObjectName("PB_config")
        self.verticalLayout_7.addWidget(self.PB_config)
        self.PB_ayuda = QtWidgets.QPushButton(self.frame_menucontroles)
        self.PB_ayuda.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_ayuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Iconos/Ayuda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ayuda.setIcon(icon8)
        self.PB_ayuda.setObjectName("PB_ayuda")
        self.verticalLayout_7.addWidget(self.PB_ayuda)
        spacerItem2 = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.PB_apagar = QtWidgets.QPushButton(self.frame_menucontroles)
        self.PB_apagar.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_apagar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_apagar.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Iconos/1x/Apagar_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_apagar.setIcon(icon9)
        self.PB_apagar.setIconSize(QtCore.QSize(120, 30))
        self.PB_apagar.setObjectName("PB_apagar")
        self.verticalLayout_7.addWidget(self.PB_apagar)
        self.horizontalLayout_4.addWidget(self.frame_menucontroles)
        self.frame_4 = QtWidgets.QFrame(self.frame_cuerpo)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 380))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_izquierdo = QtWidgets.QFrame(self.frame_3)
        self.frame_izquierdo.setMaximumSize(QtCore.QSize(62, 16777215))
        self.frame_izquierdo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_izquierdo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_izquierdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_izquierdo.setObjectName("frame_izquierdo")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_izquierdo)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.PB_left = QtWidgets.QPushButton(self.frame_izquierdo)
        self.PB_left.setMinimumSize(QtCore.QSize(50, 50))
        self.PB_left.setMaximumSize(QtCore.QSize(62, 62))
        self.PB_left.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_left.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_left.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Iconos/flecha_izquierda.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_left.setIcon(icon10)
        self.PB_left.setObjectName("PB_left")
        self.verticalLayout_5.addWidget(self.PB_left)
        spacerItem4 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_5.addWidget(self.frame_izquierdo)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_7)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_4.addWidget(self.graphicsView)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.frame_derecho = QtWidgets.QFrame(self.frame_3)
        self.frame_derecho.setMaximumSize(QtCore.QSize(62, 16777215))
        self.frame_derecho.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_derecho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_derecho.setObjectName("frame_derecho")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_derecho)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.PB_right = QtWidgets.QPushButton(self.frame_derecho)
        self.PB_right.setMinimumSize(QtCore.QSize(50, 50))
        self.PB_right.setMaximumSize(QtCore.QSize(62, 62))
        self.PB_right.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_right.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Iconos/flecha_derecha.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_right.setIcon(icon11)
        self.PB_right.setObjectName("PB_right")
        self.verticalLayout_6.addWidget(self.PB_right)
        spacerItem6 = QtWidgets.QSpacerItem(20, 153, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_5.addWidget(self.frame_derecho)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 12)
        self.horizontalLayout_5.setStretch(2, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_22 = QtWidgets.QFrame(self.frame_5)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.label_8 = QtWidgets.QLabel(self.frame_22)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 241, 20))
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        self.label_11.setGeometry(QtCore.QRect(90, 110, 91, 20))
        self.label_11.setObjectName("label_11")
        self.PB_caja = QtWidgets.QPushButton(self.frame_22)
        self.PB_caja.setGeometry(QtCore.QRect(10, 150, 61, 61))
        self.PB_caja.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Iconos/Caja.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_caja.setIcon(icon12)
        self.PB_caja.setIconSize(QtCore.QSize(50, 50))
        self.PB_caja.setObjectName("PB_caja")
        self.label_9 = QtWidgets.QLabel(self.frame_22)
        self.label_9.setGeometry(QtCore.QRect(90, 70, 111, 20))
        self.label_9.setObjectName("label_9")
        self.PB_beta = QtWidgets.QPushButton(self.frame_22)
        self.PB_beta.setGeometry(QtCore.QRect(10, 70, 61, 61))
        self.PB_beta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_beta.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Iconos/Beta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_beta.setIcon(icon13)
        self.PB_beta.setIconSize(QtCore.QSize(50, 50))
        self.PB_beta.setObjectName("PB_beta")
        self.label_10 = QtWidgets.QLabel(self.frame_22)
        self.label_10.setGeometry(QtCore.QRect(90, 150, 111, 20))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.frame_22)
        self.label_12.setGeometry(QtCore.QRect(90, 190, 91, 20))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.frame_22)
        self.frame_20 = QtWidgets.QFrame(self.frame_5)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 180, 121, 40))
        self.checkBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.CB_Camaras = QtWidgets.QCheckBox(self.frame_20)
        self.CB_Camaras.setGeometry(QtCore.QRect(10, 60, 121, 50))
        self.CB_Camaras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CB_Camaras.setText("")
        self.CB_Camaras.setObjectName("CB_Camaras")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 120, 121, 40))
        font = QtGui.QFont()
        font.setBold(False)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_4.setGeometry(QtCore.QRect(140, 60, 121, 40))
        self.checkBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_6.setGeometry(QtCore.QRect(140, 180, 121, 40))
        self.checkBox_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_5.setGeometry(QtCore.QRect(140, 120, 121, 40))
        self.checkBox_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.label_13 = QtWidgets.QLabel(self.frame_20)
        self.label_13.setGeometry(QtCore.QRect(70, 20, 171, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_20)
        self.label_14.setGeometry(QtCore.QRect(60, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: black;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_20)
        self.label_15.setGeometry(QtCore.QRect(60, 130, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: black;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_20)
        self.label_16.setGeometry(QtCore.QRect(60, 190, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: black;")
        self.label_16.setObjectName("label_16")
        self.label_21 = QtWidgets.QLabel(self.frame_20)
        self.label_21.setGeometry(QtCore.QRect(190, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: black;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.frame_20)
        self.label_22.setGeometry(QtCore.QRect(190, 130, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: black;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_20)
        self.label_23.setGeometry(QtCore.QRect(190, 190, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: black;")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_5)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.PB_EMER = QtWidgets.QPushButton(self.frame_21)
        self.PB_EMER.setGeometry(QtCore.QRect(10, 10, 251, 221))
        self.PB_EMER.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_EMER.setStyleSheet("background-color: transparent;")
        self.PB_EMER.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Iconos/Start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_EMER.setIcon(icon14)
        self.PB_EMER.setIconSize(QtCore.QSize(200, 200))
        self.PB_EMER.setObjectName("PB_EMER")
        self.horizontalLayout_7.addWidget(self.frame_21)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(310, 390, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.page_4)
        self.pushButton.setGeometry(QtCore.QRect(140, 20, 621, 361))
        self.pushButton.setStyleSheet("background-color: transparent;")
        self.pushButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Iconos/Robiotec.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon15)
        self.pushButton.setIconSize(QtCore.QSize(350, 350))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(2)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_16 = QtWidgets.QFrame(self.page_3)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_24 = QtWidgets.QFrame(self.frame_17)
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_24)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.PB_grid = QtWidgets.QPushButton(self.frame_24)
        self.PB_grid.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setBold(True)
        self.PB_grid.setFont(font)
        self.PB_grid.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_grid.setObjectName("PB_grid")
        self.horizontalLayout_6.addWidget(self.PB_grid)
        self.verticalLayout_15.addWidget(self.frame_24)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.GV_camara1 = QtWidgets.QGraphicsView(self.frame_19)
        self.GV_camara1.setObjectName("GV_camara1")
        self.verticalLayout_18.addWidget(self.GV_camara1)
        self.verticalLayout_15.addWidget(self.frame_19)
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.GV_camara2 = QtWidgets.QGraphicsView(self.frame_23)
        self.GV_camara2.setObjectName("GV_camara2")
        self.verticalLayout_17.addWidget(self.GV_camara2)
        self.verticalLayout_15.addWidget(self.frame_23)
        self.verticalLayout_15.setStretch(0, 1)
        self.verticalLayout_15.setStretch(1, 5)
        self.verticalLayout_15.setStretch(2, 5)
        self.verticalLayout_11.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_16)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_fondo = QtWidgets.QFrame(self.frame_18)
        self.frame_fondo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fondo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fondo.setObjectName("frame_fondo")
        self.label_6 = QtWidgets.QLabel(self.frame_fondo)
        self.label_6.setGeometry(QtCore.QRect(100, 30, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_fondo)
        self.label_7.setGeometry(QtCore.QRect(140, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.QS_iluminacion = QtWidgets.QSlider(self.frame_fondo)
        self.QS_iluminacion.setGeometry(QtCore.QRect(70, 180, 201, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QS_iluminacion.setFont(font)
        self.QS_iluminacion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QS_iluminacion.setStyleSheet("")
        self.QS_iluminacion.setMaximum(100)
        self.QS_iluminacion.setPageStep(5)
        self.QS_iluminacion.setOrientation(QtCore.Qt.Horizontal)
        self.QS_iluminacion.setObjectName("QS_iluminacion")
        self.PB_fondo = QtWidgets.QPushButton(self.frame_fondo)
        self.PB_fondo.setGeometry(QtCore.QRect(260, 78, 71, 45))
        self.PB_fondo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_fondo.setObjectName("PB_fondo")
        self.L_iluminacion = QtWidgets.QLabel(self.frame_fondo)
        self.L_iluminacion.setGeometry(QtCore.QRect(280, 180, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_iluminacion.setFont(font)
        self.L_iluminacion.setObjectName("L_iluminacion")
        self.SB_1 = QtWidgets.QSpinBox(self.frame_fondo)
        self.SB_1.setGeometry(QtCore.QRect(50, 80, 61, 41))
        self.SB_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SB_1.setMaximum(255)
        self.SB_1.setObjectName("SB_1")
        self.SB_2 = QtWidgets.QSpinBox(self.frame_fondo)
        self.SB_2.setGeometry(QtCore.QRect(120, 80, 61, 41))
        self.SB_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SB_2.setMaximum(255)
        self.SB_2.setObjectName("SB_2")
        self.SB_3 = QtWidgets.QSpinBox(self.frame_fondo)
        self.SB_3.setGeometry(QtCore.QRect(190, 80, 61, 41))
        self.SB_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SB_3.setMinimum(0)
        self.SB_3.setMaximum(255)
        self.SB_3.setObjectName("SB_3")
        self.L_iluminacion_2 = QtWidgets.QLabel(self.frame_fondo)
        self.L_iluminacion_2.setGeometry(QtCore.QRect(280, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_iluminacion_2.setFont(font)
        self.L_iluminacion_2.setObjectName("L_iluminacion_2")
        self.QS_iluminacion_2 = QtWidgets.QSlider(self.frame_fondo)
        self.QS_iluminacion_2.setGeometry(QtCore.QRect(70, 210, 201, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QS_iluminacion_2.setFont(font)
        self.QS_iluminacion_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QS_iluminacion_2.setStyleSheet("")
        self.QS_iluminacion_2.setMaximum(100)
        self.QS_iluminacion_2.setPageStep(5)
        self.QS_iluminacion_2.setOrientation(QtCore.Qt.Horizontal)
        self.QS_iluminacion_2.setObjectName("QS_iluminacion_2")
        self.L_iluminacion_3 = QtWidgets.QLabel(self.frame_fondo)
        self.L_iluminacion_3.setGeometry(QtCore.QRect(280, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_iluminacion_3.setFont(font)
        self.L_iluminacion_3.setObjectName("L_iluminacion_3")
        self.QS_iluminacion_3 = QtWidgets.QSlider(self.frame_fondo)
        self.QS_iluminacion_3.setGeometry(QtCore.QRect(70, 240, 201, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QS_iluminacion_3.setFont(font)
        self.QS_iluminacion_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QS_iluminacion_3.setStyleSheet("")
        self.QS_iluminacion_3.setMaximum(100)
        self.QS_iluminacion_3.setPageStep(5)
        self.QS_iluminacion_3.setOrientation(QtCore.Qt.Horizontal)
        self.QS_iluminacion_3.setObjectName("QS_iluminacion_3")
        self.L_iluminacion_4 = QtWidgets.QLabel(self.frame_fondo)
        self.L_iluminacion_4.setGeometry(QtCore.QRect(280, 270, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_iluminacion_4.setFont(font)
        self.L_iluminacion_4.setObjectName("L_iluminacion_4")
        self.QS_iluminacion_4 = QtWidgets.QSlider(self.frame_fondo)
        self.QS_iluminacion_4.setGeometry(QtCore.QRect(70, 270, 201, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.QS_iluminacion_4.setFont(font)
        self.QS_iluminacion_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QS_iluminacion_4.setStyleSheet("")
        self.QS_iluminacion_4.setMaximum(100)
        self.QS_iluminacion_4.setPageStep(5)
        self.QS_iluminacion_4.setOrientation(QtCore.Qt.Horizontal)
        self.QS_iluminacion_4.setObjectName("QS_iluminacion_4")
        self.horizontalLayout_8.addWidget(self.frame_fondo)
        self.frame_banda = QtWidgets.QFrame(self.frame_18)
        self.frame_banda.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_banda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_banda.setObjectName("frame_banda")
        self.label_17 = QtWidgets.QLabel(self.frame_banda)
        self.label_17.setGeometry(QtCore.QRect(112, 30, 188, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.PB_banda = QtWidgets.QPushButton(self.frame_banda)
        self.PB_banda.setGeometry(QtCore.QRect(231, 80, 80, 31))
        self.PB_banda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_banda.setObjectName("PB_banda")
        self.label_18 = QtWidgets.QLabel(self.frame_banda)
        self.label_18.setGeometry(QtCore.QRect(60, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.frame_banda)
        self.label_20.setGeometry(QtCore.QRect(105, 190, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.SB_saranda = QtWidgets.QSpinBox(self.frame_banda)
        self.SB_saranda.setGeometry(QtCore.QRect(120, 240, 101, 41))
        self.SB_saranda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SB_saranda.setObjectName("SB_saranda")
        self.label_24 = QtWidgets.QLabel(self.frame_banda)
        self.label_24.setGeometry(QtCore.QRect(80, 244, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.PB_saranda = QtWidgets.QPushButton(self.frame_banda)
        self.PB_saranda.setGeometry(QtCore.QRect(229, 247, 71, 31))
        self.PB_saranda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PB_saranda.setObjectName("PB_saranda")
        self.SP_banda = QtWidgets.QSpinBox(self.frame_banda)
        self.SP_banda.setGeometry(QtCore.QRect(120, 80, 101, 31))
        self.SP_banda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SP_banda.setObjectName("SP_banda")
        self.horizontalLayout_8.addWidget(self.frame_banda)
        self.verticalLayout_11.addWidget(self.frame_18)
        self.verticalLayout_11.setStretch(0, 3)
        self.verticalLayout_11.setStretch(1, 4)
        self.verticalLayout_16.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.page_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_14.setSpacing(2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_14.addWidget(self.label_2)
        self.verticalLayout_9.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_14 = QtWidgets.QFrame(self.frame_9)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.PB_ciclo = QtWidgets.QPushButton(self.frame_14)
        self.PB_ciclo.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.PB_ciclo.setFont(font)
        self.PB_ciclo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Iconos/Ciclo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ciclo.setIcon(icon16)
        self.PB_ciclo.setCheckable(False)
        self.PB_ciclo.setAutoRepeat(False)
        self.PB_ciclo.setObjectName("PB_ciclo")
        self.verticalLayout_12.addWidget(self.PB_ciclo)
        self.gridLayout.addWidget(self.frame_14, 1, 0, 1, 1)
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.PB_todas = QtWidgets.QPushButton(self.frame_13)
        self.PB_todas.setMinimumSize(QtCore.QSize(0, 120))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.PB_todas.setFont(font)
        self.PB_todas.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Iconos/Todas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_todas.setIcon(icon17)
        self.PB_todas.setObjectName("PB_todas")
        self.verticalLayout_13.addWidget(self.PB_todas)
        self.gridLayout.addWidget(self.frame_13, 0, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_9)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        # Simplificacionmpara los Botones de la valvula
        self.buttons = {}
        button_configs = [
            ("1", 0, 0, 75), ("2", 0, 1, 75), ("3", 0, 2, 75), ("4", 0, 3, None),
            ("5", 0, 4, 75), ("6", 0, 5, None), ("7", 0, 6, None), ("8", 0, 7, None),
            ("9", 0, 8, None), ("10", 1, 0, 75), ("11", 1, 1, 75), ("12", 1, 2, 75),
            ("13", 1, 3, None), ("14", 1, 4, 75), ("15", 1, 5, None), ("16", 1, 6, None),
            ("17", 1, 7, None), ("18", 1, 8, None), ("19", 2, 0, 75), ("20", 2, 1, 75),
            ("21", 2, 2, 75), ("22", 2, 3, None), ("23", 2, 4, 75), ("24", 2, 5, None),
            ("25", 2, 6, None), ("26", 2, 7, None), ("27", 2, 8, None), ("28", 3, 0, 75),
            ("29", 3, 1, 75), ("30", 3, 2, 75), ("31", 3, 3, None), ("32", 3, 4, 75),
            ("33", 3, 5, None), ("34", 3, 6, None), ("35", 3, 7, None), ("36", 3, 8, None),
            ("37", 4, 0, 75), ("38", 4, 1, 75), ("39", 4, 2, 75), ("40", 4, 3, None),
            ("41", 4, 4, 75), ("42", 4, 5, None), ("43", 4, 6, None), ("44", 4, 7, None),
            ("45", 4, 8, None), ("46", 5, 0, 75), ("47", 5, 1, 75), ("48", 5, 2, 75),
            ("49", 5, 3, None), ("50", 5, 4, 75), ("51", 5, 5, None), ("52", 5, 6, None),
            ("53", 5, 7, None), ("54", 5, 8, None), ("55", 6, 0, 75), ("56", 6, 1, 75),
            ("57", 6, 2, 75), ("58", 6, 3, None), ("59", 6, 4, 75), ("60", 6, 5, None),
            ("61", 6, 6, None), ("62", 6, 7, None), ("63", 6, 8, None), ("64", 8, 0, 75),
            ("65", 8, 1, 75), ("66", 8, 2, 75), ("67", 8, 3, 80), ("68", 8, 4, 75),
            ("69", 8, 5, 80), ("70", 8, 6, None), ("71", 8, 7, None), ("72", 8, 8, None),
            ("73", 9, 0, 75), ("74", 9, 1, 75), ("75", 9, 2, 75), ("76", 9, 3, None),
            ("77", 9, 4, 75), ("78", 9, 5, 80), ("79", 9, 6, 80), ("80", 9, 7, 80),
            ("81", 9, 8, 80), ("82", 10, 0, 75), ("83", 10, 1, 75), ("84", 10, 2, 75),
            ("85", 10, 3, 80), ("86", 10, 4, 75), ("87", 10, 5, None), ("88", 10, 6, 80),
            ("89", 10, 7, 80), ("90", 10, 8, None), ("91", 12, 0, 75), ("92", 12, 1, 75),
            ("93", 12, 2, 75), ("94", 12, 3, 80), ("95", 12, 4, 75), ("96", 12, 5, 80),
            ("97", 12, 6, 80), ("98", 12, 7, None), ("99", 12, 8, 80),
        ]

        for config in button_configs:
            name_suffix, row, col, max_width = config
            button = QtWidgets.QPushButton(self.frame_15)
            button.setMinimumSize(QtCore.QSize(0, 35))
            button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            button.setObjectName(f"PB_{name_suffix}")
            
            if max_width is not None:
                button.setMaximumSize(QtCore.QSize(max_width, 16777215))
                
            self.buttons[f"PB_{name_suffix}"] = button
            self.gridLayout_2.addWidget(button, row, col, 1, 1)
        
        self.gridLayout.addWidget(self.frame_15, 0, 1, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout_9.addWidget(self.frame_9)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 8)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.page_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setGeometry(QtCore.QRect(390, 10, 63, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_10.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_8)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_10.addWidget(self.frame_12)
        self.verticalLayout_10.setStretch(0, 2)
        self.verticalLayout_10.setStretch(1, 10)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.verticalLayout_8.setStretch(0, 3)
        self.verticalLayout_8.setStretch(1, 2)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout_4.setStretch(0, 2)
        self.verticalLayout.addWidget(self.frame_cuerpo)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 12)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PB_produc.setText(_translate("MainWindow", " Producción"))
        self.PB_test.setText(_translate("MainWindow", " Testeo"))
        self.PB_config.setText(_translate("MainWindow", " Configuración"))
        self.PB_ayuda.setText(_translate("MainWindow", " Ayuda"))
        self.PB_apagar.setText(_translate("MainWindow", "  APAGAR"))
        self.label.setText(_translate("MainWindow", "Camara #1"))
        self.label_8.setText(_translate("MainWindow", "Selecciona lo que quieres procesar"))
        self.label_11.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "# de Betas:"))
        self.label_10.setText(_translate("MainWindow", "# de Cajas:"))
        self.label_12.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Activaciones Individuales"))
        self.label_14.setText(_translate("MainWindow", "Camaras"))
        self.label_15.setText(_translate("MainWindow", "Valvulas"))
        self.label_16.setText(_translate("MainWindow", "Banda"))
        self.label_21.setText(_translate("MainWindow", "Saranda"))
        self.label_22.setText(_translate("MainWindow", "Alimentad"))
        self.label_23.setText(_translate("MainWindow", "Rampa"))
        self.label_5.setText(_translate("MainWindow", "Ayuda"))
        self.label_4.setText(_translate("MainWindow", "Alineaciòn de las camaras"))
        self.PB_grid.setText(_translate("MainWindow", "Grid"))
        self.label_6.setText(_translate("MainWindow", "Color de Fondo (RGB)"))
        self.label_7.setText(_translate("MainWindow", "Iluminación"))
        self.PB_fondo.setText(_translate("MainWindow", "Cargar"))
        self.L_iluminacion.setText(_translate("MainWindow", "0%"))
        self.L_iluminacion_2.setText(_translate("MainWindow", "0%"))
        self.L_iluminacion_3.setText(_translate("MainWindow", "0%"))
        self.L_iluminacion_4.setText(_translate("MainWindow", "0%"))
        self.label_17.setText(_translate("MainWindow", "Velocidad de la Banda"))
        self.PB_banda.setText(_translate("MainWindow", "Cargar"))
        self.label_18.setText(_translate("MainWindow", "RPM:"))
        self.label_20.setText(_translate("MainWindow", "Velocidad de la Saranda"))
        self.label_24.setText(_translate("MainWindow", "Hz:"))
        self.PB_saranda.setText(_translate("MainWindow", "Cargar"))
        self.label_2.setText(_translate("MainWindow", "Valvulas"))
        self.PB_ciclo.setText(_translate("MainWindow", "Ciclo"))
        self.PB_todas.setText(_translate("MainWindow", "Todas"))
        
        buttonText = [58, 29, 78, 81, 34, 42, 55, 17, 10, 35, 77, 57, 38, 48, 60, 18, 83, 45, 12, 25, 41, 89, 7, 40, 27, 79, 50, 72, 66, 16, 22, 31, 80, 47, 1, 5, 11, 74, 69, 32, 9, 13, 49, 21, 8, 39, 46, 76, 61, 3, 82, 65, 71, 64, 63, 73, 87, 19, 14, 51, 68, 85, 86, 33, 62, 4, 88, 2, 30, 28, 37, 56, 36, 44, 53, 59, 52, 70, 90, 15, 20, 75, 54, 67, 84, 24, 23, 26, 43, 92, 6, 91, 93, 94, 95, 96, 97, 98, 99]
        for salon in buttonText:
            button_name = f"PB_{salon}"
            self.buttons[button_name].setText(_translate("MainWindow", f"Sal. {salon}"))

        self.label_3.setText(_translate("MainWindow", "Motores"))

    #* Metodo para llamar los Stylos
    def stylos(self):
        url = "src/style.qss"
        try:
            with open(url, "r", encoding="utf-8") as file:
                css = file.read()
                return css
        except:
            print("No cargo el archivo")
            return ""

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
