[project]
name = "interfaz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.11.0.86",
    "pymodbus>=3.8.6",
    "pyqt5>=5.15.11",
    "pyserial>=3.5",
    "serial>=0.0.97",
]
